[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snf_simulations"
version = "0.1.0"
description = "Simulate antineutrino spectra for different compositions of spent nuclear fuel."
authors = [
    {name = "Zuzanna Leliwa", email = "zleliwa1@sheffield.ac.uk"},
    {name = "Abigail Power", email = "apower3@sheffield.ac.uk"},
    {name = "Liz Kneale", email = "e.kneale@sheffield.ac.uk"},
    {name = "Martin Dyer", email = "martin.dyer@sheffield.ac.uk"},
]
maintainers = [
    {name = "Liz Kneale", email = "e.kneale@sheffield.ac.uk"},
]
readme = "README.md"
license = "BSD-3-Clause"
license-files = [
    'LICENSE.txt'
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[project.scripts]
snf-sim = "snf_simulations.scripts.command_line:main"

[project.urls]
source = "https://github.com/ekneale/SNF-simulations"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"snf_simulations.data.spec_data" = ["*.txt"]
